version: 2

jobs:
  python_3_6:
    shell: /bin/bash --login
    macos:
      xcode: '9.4.1'
    steps:
    - checkout
    - run: |
        brew update
        python --version
        sudo -H pip install --upgrade virtualenv
        brew install pyenv
        echo 'eval "$(pyenv init --path)"' >> ~/.bash_profile
        echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
        source ~/.bash_profile
        pyenv install 3.6.5
        pyenv versions
        pyenv global 3.6.5
        python --version
    - run: python setup.py install
    - run: python setup.py test

  python_3_7:
    shell: /bin/bash --login
    macos:
      xcode: '9.4.1'
    steps:
    - checkout
    - run: |
        brew update
        python --version
        sudo -H pip install --upgrade virtualenv
        brew install pyenv
        echo 'eval "$(pyenv init --path)"' >> ~/.bash_profile
        echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
        source ~/.bash_profile
        pyenv install 3.7.10
        pyenv versions
        pyenv global 3.7.10
        python --version
    - run: python setup.py install
    - run: python setup.py test

  python_3_8:
    shell: /bin/bash --login
    macos:
      xcode: '9.4.1'
    steps:
    - checkout
    - run: |
        brew update
        python --version
        sudo -H pip install --upgrade virtualenv
        brew install pyenv
        echo 'eval "$(pyenv init --path)"' >> ~/.bash_profile
        echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
        source ~/.bash_profile
        pyenv install 3.8.10
        pyenv versions
        pyenv global 3.8.10
        python --version
    - run: python setup.py install
    - run: python setup.py test

  python_3_9:
    shell: /bin/bash --login
    macos:
      xcode: '9.4.1'
    steps:
    - checkout
    - run: |
        brew update
        python --version
        sudo -H pip install --upgrade virtualenv
        brew install pyenv
        echo 'eval "$(pyenv init --path)"' >> ~/.bash_profile
        echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
        source ~/.bash_profile
        pyenv install 3.9.5
        pyenv versions
        pyenv global 3.9.5
        python --version
    - run: python setup.py install
    - run: python setup.py test

workflows:
  version: 2
  python_matrix_build:
    jobs:
      - python_3_6
      - python_3_7
      - python_3_8
      - python_3_9
